apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-node
spec:
  template:
    metadata:
      labels:
        app: kube-node
        tier: backend
        track: stable
    spec:
      containers:
        - name: kube-node
          image: "kube-playground:v0.0.5"
          ports:
            - name: http
              containerPort: 8080

